

/* Create Tables */

CREATE TABLE BEDS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	ROOM_ID INT NOT NULL COMMENT 'room_id',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	NAME CHAR(30) COMMENT 'name',
	PRIMARY KEY (ID)
) COMMENT = 'beds';


CREATE TABLE BED_USAGE
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	BED_ID INT NOT NULL COMMENT 'bed_id',
	PATIENT_ID INT NOT NULL COMMENT 'patient_id',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	START_DATE DATE NOT NULL COMMENT 'start_date',
	END_DATE DATE NOT NULL COMMENT 'end_date',
	STATUS TINYINT DEFAULT 0 NOT NULL COMMENT 'status',
	PRIMARY KEY (ID)
) COMMENT = 'bed_usage';


CREATE TABLE DOCTORS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	STAFF_ID INT NOT NULL COMMENT 'staff_id',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	PRIMARY KEY (ID)
) COMMENT = 'doctors';


CREATE TABLE INPATINET_RECORDS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	PATIENT_ID INT NOT NULL COMMENT 'patient_id',
	BED_ID INT NOT NULL COMMENT 'bed_id',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	ADMITTED_DATE DATE NOT NULL COMMENT 'admitted_date',
	DISCHARGED_DATE DATE COMMENT 'discharged_date',
	DISEASE_NAME VARCHAR(500) NOT NULL COMMENT 'disease_name',
	TYPE_OF_TREATMENT VARCHAR(1000) NOT NULL COMMENT 'type_of_treatment',
	MEDICINE_GIVEN BOOLEAN NOT NULL COMMENT 'medicine_given',
	MEDICINE_NAME VARCHAR(500) COMMENT 'medicine_name',
	SPECIAL_NOTES VARCHAR(1000) COMMENT 'special_notes',
	BILLING_AMOUNT CHAR(30) NOT NULL COMMENT 'billing_amount',
	PRIMARY KEY (ID)
) COMMENT = 'inpatinet_records';


CREATE TABLE OUTPATIENT_RECORDS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	PATIENT_ID INT NOT NULL COMMENT 'patient_id',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	VISIT_DATA DATE NOT NULL COMMENT 'visit_data',
	DISEASE_NAME VARCHAR(500) NOT NULL COMMENT 'disease_name',
	TYPE_OF_TREATMENT VARCHAR(1000) NOT NULL COMMENT 'type_of_treatment',
	MEDICINE_GIVEN BOOLEAN NOT NULL COMMENT 'medicine_given',
	MEDICINE_NAME VARCHAR(500) COMMENT 'medicine_name',
	SPECIAL_NOTES VARCHAR(1000) COMMENT 'special_notes',
	AMBULANCE_SERVICE_USED BOOLEAN NOT NULL COMMENT 'ambulance_service_used',
	BILLING_AMOUNT CHAR(30) NOT NULL COMMENT 'billing_amount',
	PRIMARY KEY (ID)
) COMMENT = 'outpatient_records';


CREATE TABLE PATIENTS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	USER_ID INT NOT NULL COMMENT 'user_id',
	DOCTOR_ID INT NOT NULL COMMENT 'doctor_id',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	PRIMARY KEY (ID)
) COMMENT = 'patients';


CREATE TABLE ROOMS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	NAME CHAR(30) COMMENT 'name',
	FLOOR TINYINT COMMENT 'floor',
	PRIMARY KEY (ID)
) COMMENT = 'rooms';


CREATE TABLE SHIFTS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	STAFF_ID INT NOT NULL COMMENT 'staff_id',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	CLOCK_IN_TIME DATETIME NOT NULL COMMENT 'clock_in_time',
	CLOCK_OUT_TIME DATETIME COMMENT 'clock_out_time',
	STATUS TINYINT DEFAULT 0 NOT NULL COMMENT 'status',
	PRIMARY KEY (ID)
) COMMENT = 'shifts';


CREATE TABLE STAFF
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	USER_ID INT NOT NULL COMMENT 'user_id',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	QUALIFICATION CHAR(50) NOT NULL COMMENT 'qualification',
	CERTIFICATION_EXPIRATIONS DATE NOT NULL COMMENT 'certification_expirations',
	CELL_PHONE_NUMBER CHAR(20) COMMENT 'cell_phone_number',
	EMAIL_ADDRESS CHAR(50) COMMENT 'email_address',
	PAYROLL CHAR(30) NOT NULL COMMENT 'payroll',
	PERSONAL_DETAILS VARCHAR(500) COMMENT 'personal_details',
	IS_DOCTOR BOOLEAN NOT NULL COMMENT 'is_doctor',
	PRIMARY KEY (ID)
) COMMENT = 'staff';


CREATE TABLE USERS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	LOGIN_NAME CHAR(30) NOT NULL UNIQUE COMMENT 'login_name',
	PASSWORD CHAR(50) NOT NULL COMMENT 'password',
	ROLE TINYINT NOT NULL COMMENT 'role',
	FIRST_NAME CHAR(30) NOT NULL COMMENT 'first_name',
	MIDDLE_NAME CHAR(30) COMMENT 'middle_name',
	LAST_NAME CHAR(30) NOT NULL COMMENT 'last_name',
	SOCIAL_SECURITY_NUMBER CHAR(15) NOT NULL UNIQUE COMMENT 'social_security_number',
	ADDRESS CHAR(100) COMMENT 'address',
	PRIMARY KEY (ID)
) COMMENT = 'users';



/* Create Foreign Keys */

ALTER TABLE BED_USAGE
	ADD CONSTRAINT FK_BED_USAGE_BEDS FOREIGN KEY (BED_ID)
	REFERENCES BEDS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INPATINET_RECORDS
	ADD CONSTRAINT FK_INPATINET_RECORDS_BEDS FOREIGN KEY (BED_ID)
	REFERENCES BEDS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATIENTS
	ADD CONSTRAINT FK_PATIENTS_DOCTORS FOREIGN KEY (DOCTOR_ID)
	REFERENCES DOCTORS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BED_USAGE
	ADD CONSTRAINT FK_BED_USAGE_PATIENTS FOREIGN KEY (PATIENT_ID)
	REFERENCES PATIENTS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INPATINET_RECORDS
	ADD CONSTRAINT FK_INPATINET_RECORDS_PATIENTS FOREIGN KEY (PATIENT_ID)
	REFERENCES PATIENTS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OUTPATIENT_RECORDS
	ADD CONSTRAINT FK_OUTPATIENT_RECORDS_PATIENTS FOREIGN KEY (PATIENT_ID)
	REFERENCES PATIENTS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BEDS
	ADD CONSTRAINT FK_BEDS_ROOMS FOREIGN KEY (ROOM_ID)
	REFERENCES ROOMS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DOCTORS
	ADD CONSTRAINT FK_DOCTORS_STAFF FOREIGN KEY (STAFF_ID)
	REFERENCES STAFF (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SHIFTS
	ADD CONSTRAINT FK_SHIFTS_STAFF FOREIGN KEY (STAFF_ID)
	REFERENCES STAFF (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATIENTS
	ADD CONSTRAINT FK_PATIENTS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE STAFF
	ADD CONSTRAINT FK_STAFF_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



